USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE TEST_DB;

--Masking Policies
ALTER TABLE CUSTOMERS MODIFY COLUMN CONTACT_NAME UNSET MASKING POLICY;
DROP MASKING POLICY IF EXISTS CUSTOMER_MASK;
CREATE MASKING POLICY CUSTOMER_MASK AS (VAL CHARACTER VARYING(30)) RETURNS CHARACTER VARYING(30) ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATASCIENTIST') THEN '**********'
        ELSE VAL
    END;
    
ALTER TABLE CUSTOMERS ALTER CONTACT_NAME SET MASKING POLICY CUSTOMER_MASK;

 
GRANT SELECT ON TABLE CUSTOMERS TO DATASCIENTIST;
GRANT USAGE, MONITOR ON DATABASE TEST_DB TO DATASCIENTIST;
GRANT USAGE, MONITOR ON ALL SCHEMAS IN DATABASE TEST_DB TO DATASCIENTIST;



USE ROLE DATASCIENTIST;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE TEST_DB;

SELECT * FROM CUSTOMERS;

USE ROLE CUST_DATASCIENTIST;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;

SELECT * FROM CUSTOMERS;
